import Link from "next/link";
import type { EditorIdentity } from "@/modules/auth/editor-auth";
import type { SourceSubmissionReview } from "@/modules/preparation/source-submission-read-model";
import { EditorHeader } from "../../editor-workspace";
import { AcceptProposalPanel } from "./accept-proposal-panel";
import { AcceptSourcePanel } from "./accept-source-panel";
import { AcceptCandidateClaimPanel } from "./accept-candidate-claim-panel";
import type { SourceAcceptanceActionState } from "./source-actions";
import type { ProposalAcceptanceActionState } from "./actions";
import type { CandidateClaimAcceptanceActionState } from "./candidate-claim-actions";
import type { CandidateClaimAcceptanceContext } from "@/modules/evidence/candidate-claim-acceptance-context";

type ProposalAcceptanceAction = (state: ProposalAcceptanceActionState, formData: FormData) => Promise<ProposalAcceptanceActionState>;
type SourceAcceptanceAction = (state: SourceAcceptanceActionState, formData: FormData) => Promise<SourceAcceptanceActionState>;
type CandidateClaimAcceptanceAction = (state: CandidateClaimAcceptanceActionState, formData: FormData) => Promise<CandidateClaimAcceptanceActionState>;

export function SourceSubmissionReviewPageContent({ editor, submission, acceptAction, acceptSourceAction, candidateContext, candidateClaimAction }: Readonly<{ editor: EditorIdentity; submission: SourceSubmissionReview; acceptAction?: ProposalAcceptanceAction; acceptSourceAction?: SourceAcceptanceAction; candidateContext?: CandidateClaimAcceptanceContext; candidateClaimAction?: (candidateIndex: number) => CandidateClaimAcceptanceAction }>) {
  return <><EditorHeader editor={editor} /><main id="main-content" className="editor-shell submission-review-shell"><Link className="editor-back-link" href="/editor">← Back to queue</Link><header className="submission-review-heading"><p className="eyebrow">Source Submission</p><h1>Review a prepared proposal</h1><p>These are worker suggestions, not accepted Sources, Claims, taxonomy, or publishable content.</p></header><div className="submission-review-layout"><div className="submission-review-reading"><section className="submission-provenance"><p className="section-kicker">Submitted material</p><h2>Provenance stays with the material</h2><dl><Fact label="Kind" value={submission.kind} /><Fact label="Reference" value={submission.originalIdentifier} /><Fact label="Submitted by" value={submission.submittedBy} /><Fact label="Submitted" value={date(submission.submittedAt)} />{submission.retrievedAt ? <Fact label="Retrieved" value={date(submission.retrievedAt)} /> : null}<Fact label="Processing" value={<><span className="status-token">{submission.processingStatus.replaceAll("-", " ")}</span>{submission.resultState ? ` ${submission.resultState.replaceAll("-", " ")}` : ""}</>} /><Fact label="Rights note" value={submission.rightsNote} /></dl></section>{submission.proposal ? <Proposal proposal={submission.proposal} /> : <section className="submission-awaiting"><p className="section-kicker">Preparation</p><h2>No prepared proposal is available yet.</h2><p>The material remains a Source Submission. It has not become evidence or a draft.</p></section>}{submission.proposal&&submission.preparedOutputFingerprint&&acceptAction?<AcceptProposalPanel suggestedTopic={submission.proposal.proposedTopic} action={acceptAction}/>:null}{submission.preparedOutputFingerprint&&acceptSourceAction?<AcceptSourcePanel action={acceptSourceAction} defaults={{title:submission.originalIdentifier,canonicalUrl:submission.kind==="url"?submission.originalIdentifier:"",rightsNote:submission.rightsNote}}/>:null}{candidateContext&&candidateClaimAction?<section className="candidate-claim-decisions"><p className="section-kicker">Candidate Claims</p><h2>Accept a Claim with its evidence</h2>{candidateContext.proposal.candidateClaims.map((candidate)=><AcceptCandidateClaimPanel key={candidate.index} candidate={candidate} revisions={candidateContext.revisionsCreatedFromSubmission} sources={candidateContext.sourcesAcceptedFromSubmission} action={candidateClaimAction(candidate.index)} />)}</section>:null}</div><aside className="suggestion-guardrail"><p className="section-kicker">Editorial boundary</p><h2>Nothing here is accepted yet.</h2><p>A proposal can help you decide what to investigate. It cannot accept a Source, verify a Claim, create a canonical Topic, or publish a Briefing.</p><p>Accepting this proposal creates only a new Draft Briefing. Source and Claim acceptance remain separate decisions.</p></aside></div></main></>;
}
function Proposal({ proposal }: Readonly<{ proposal: NonNullable<SourceSubmissionReview["proposal"]> }>) { return <><section className="proposal-classification"><p className="section-kicker">Suggested placement</p><h2>A possible place to start</h2><dl><Fact label="Suggested Topic" value={proposal.proposedTopic} />{proposal.proposedSubtopic ? <Fact label="Suggested Subtopic" value={proposal.proposedSubtopic} /> : null}<Fact label="Confidence" value={confidence(proposal.confidence)} /><Fact label="Why it was suggested" value={proposal.rationale} /></dl></section><section><p className="section-kicker">Candidate Claims</p><h2>Statements to verify, not facts to use</h2>{proposal.candidateClaims.length === 0 ? <p className="editor-empty">The worker did not suggest any Claims.</p> : <ol className="candidate-claims">{proposal.candidateClaims.map((claim, index) => <li key={`${claim.statement}-${index}`}><h3>{claim.statement}</h3><blockquote>{claim.excerpt}</blockquote><p><strong>Confidence:</strong> {confidence(claim.confidence)}</p><small>{claim.rationale}</small></li>)}</ol>}</section><section><p className="section-kicker">Proposed Briefing draft</p><h2>{proposal.draft.title}</h2><p className="proposal-template">Suggested template: {proposal.draft.templateVersion}. This is not an editorial revision.</p><div className="proposed-draft">{proposal.draft.sections.map((section, index) => <section key={`${section.section}-${index}`}><h3>{section.section}</h3><p>{section.body}</p></section>)}</div></section></>; }
function Fact({ label, value }: Readonly<{ label: string; value: React.ReactNode }>) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function date(value: string): string { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "an unknown date" : new Intl.DateTimeFormat("en-SG", { dateStyle: "medium", timeStyle: "short" }).format(parsed); }
function confidence(value: number): string { return `${Math.round(Math.max(0, Math.min(1, value)) * 100)}%`; }
