import { afterEach, describe, expect, it, vi } from "vitest";
import type { AcceptCandidateClaimRepository } from "@/modules/evidence/accept-candidate-claim-command";
import { createAcceptCandidateClaimCommand } from "@/modules/evidence/accept-candidate-claim-command";
import { buildPrivateApi, type PublicCatalogueQuery } from "./app";
import type { ServiceCredentialAuthenticator } from "./service-auth";
const auth:ServiceCredentialAuthenticator={async authenticate(x){return x==="Bearer test"?{kind:"private-service"}:null;}}; const catalogue:PublicCatalogueQuery={findPublishedBriefingBySlug:()=>undefined};
const id="123e4567-e89b-12d3-a456-426614174000", revision="123e4567-e89b-42d3-a456-426614174001", source="123e4567-e89b-42d3-a456-426614174002";
const body={idempotencyKey:"claim-acceptance:government:0:v1",actorId:"google:editor",expectedOutputFingerprint:"sha256:8bb0d4d4b9e657a7281c8026bd2ac6200277f426f8a4cf7cab4349e43d8b01a7",candidateIndex:0,briefingRevisionId:revision,acceptedSourceId:source};
describe("candidate Claim acceptance private route",()=>{const apps:ReturnType<typeof buildPrivateApi>[]=[];afterEach(async()=>{await Promise.all(apps.splice(0).map(a=>a.close()));});function app(command:ReturnType<typeof createAcceptCandidateClaimCommand>){const a=buildPrivateApi({serviceAuthenticator:auth,publicCatalogue:catalogue,candidateClaimAcceptances:command,now:()=>new Date("2026-08-08T12:00:00.000Z")});apps.push(a);return a;}
it("passes one strict server-timestamped claim decision",async()=>{const acceptCandidateClaim=vi.fn().mockResolvedValue({kind:"created",claimId:"claim",claimSupportId:"support",decisionId:"decision"});const command=createAcceptCandidateClaimCommand({async retrievePreparedCandidateClaims(){return {submissionId:id,state:"prepared",outputFingerprint:body.expectedOutputFingerprint,candidateClaims:[{statement:"Claim",excerpt:"Excerpt",confidence:.9,rationale:"Rationale"}]};},acceptCandidateClaim});const r=await app(command).inject({method:"POST",url:`/v1/editorial/source-submissions/${id}/candidate-claims/acceptance`,headers:{authorization:"Bearer test"},payload:body});expect(r.statusCode).toBe(201);expect(acceptCandidateClaim).toHaveBeenCalledWith(expect.objectContaining({...body,submissionId:id,occurredAt:"2026-08-08T12:00:00.000Z"}));expect(r.json()).toEqual({kind:"created",claimId:"claim",claimSupportId:"support",decisionId:"decision"});});
it("returns idempotent 200 and conflict 409",async()=>{const repository:AcceptCandidateClaimRepository={async retrievePreparedCandidateClaims(){return {submissionId:id,state:"prepared",outputFingerprint:body.expectedOutputFingerprint,candidateClaims:[{statement:"Claim",excerpt:"Excerpt",confidence:.9,rationale:"Rationale"}]};},async acceptCandidateClaim(){return {kind:"idempotent",claimId:"claim",claimSupportId:"support",decisionId:"decision"};}};expect((await app(createAcceptCandidateClaimCommand(repository)).inject({method:"POST",url:`/v1/editorial/source-submissions/${id}/candidate-claims/acceptance`,headers:{authorization:"Bearer test"},payload:body})).statusCode).toBe(200);const conflict=createAcceptCandidateClaimCommand({...repository,async acceptCandidateClaim(){return {kind:"proposal-conflict"};}});const r=await app(conflict).inject({method:"POST",url:`/v1/editorial/source-submissions/${id}/candidate-claims/acceptance`,headers:{authorization:"Bearer test"},payload:body});expect(r.statusCode).toBe(409);});
it("requires service auth and rejects browser timestamps",async()=>{const command=createAcceptCandidateClaimCommand({async retrievePreparedCandidateClaims(){return undefined;},async acceptCandidateClaim(){throw new Error("no");}});expect((await app(command).inject({method:"POST",url:`/v1/editorial/source-submissions/${id}/candidate-claims/acceptance`,payload:body})).statusCode).toBe(401);expect((await app(command).inject({method:"POST",url:`/v1/editorial/source-submissions/${id}/candidate-claims/acceptance`,headers:{authorization:"Bearer test"},payload:{...body,occurredAt:"browser"}})).statusCode).toBe(400);});});
