import "server-only";
import { randomUUID } from "node:crypto";
import type { EditorIdentity } from "@/modules/auth/editor-auth";
import { createPrivateApiClient, PrivateApiClientError, type PrivateApiClient } from "./private-api-client";
export type SourceMetadata=Readonly<{title:string;publisher:string;sourceType:string;canonicalUrl:string;externalIdentifier?:string;publishedAt?:string;retrievedAt:string;relation:string;rightsNote:string}>;
export type SourceAcceptanceTransport=Readonly<{accept(input:Readonly<{submissionId:string;actorId:string;idempotencyKey:string;expectedOutputFingerprint:string;source:SourceMetadata}>):Promise<Readonly<{acceptedSourceId:string}>>}>;
export type SourceAcceptanceResult=Readonly<{kind:"success";acceptedSourceId:string}>|Readonly<{kind:"invalid"|"rejected"|"unavailable";message:string}>;
export function createSourceAcceptanceBff(privateApi:Pick<PrivateApiClient,"command">):SourceAcceptanceTransport{return{async accept(input){const response=await privateApi.command<unknown>({path:`/v1/editorial/source-submissions/${encodeURIComponent(input.submissionId)}/sources`,method:"POST",body:input});if(!record(response)||typeof response.acceptedSourceId!=="string")throw new Error("Invalid Source acceptance response.");return{acceptedSourceId:response.acceptedSourceId};}};}
export async function acceptSource(editor:EditorIdentity,input:Readonly<{submissionId:string;expectedOutputFingerprint:string;confirmed:unknown;source:Record<string,unknown>}>,dependencies:Readonly<{transport?:SourceAcceptanceTransport;environment?:Readonly<Record<string,string|undefined>>;idempotencyKey?:()=>string}>={}):Promise<SourceAcceptanceResult>{const source=metadata(input.source);if(input.confirmed!=="accept-source")return{kind:"invalid",message:"Confirm that you have reviewed this Source before accepting it."};if(!uuid(input.submissionId)||!/^sha256:[a-f0-9]{64}$/.test(input.expectedOutputFingerprint)||!source)return{kind:"invalid",message:"Complete valid Source metadata before accepting."};try{const transport=dependencies.transport??fromEnvironment(dependencies.environment);const result=await transport.accept({submissionId:input.submissionId,actorId:editor.actorId,idempotencyKey:(dependencies.idempotencyKey??randomUUID)(),expectedOutputFingerprint:input.expectedOutputFingerprint,source});return{kind:"success",acceptedSourceId:result.acceptedSourceId};}catch(error){if(error instanceof PrivateApiClientError&&["not_found","conflict","validation_failed","bad_request"].includes(error.code))return{kind:"rejected",message:"This Source was not accepted. Reload the proposal and review the current evidence."};return{kind:"unavailable",message:"The editorial service is unavailable. No Source was accepted; try again shortly."};}}
function metadata(raw:Record<string,unknown>):SourceMetadata|undefined{const required=["title","publisher","sourceType","canonicalUrl","retrievedAt","relation","rightsNote"] as const;const values=Object.fromEntries(required.map(k=>[k,text(raw[k])])) as Record<typeof required[number],string|undefined>;if(Object.values(values).some(v=>!v)||!date(values.retrievedAt!))return undefined;const publishedAt=text(raw.publishedAt);if(publishedAt&&!date(publishedAt))return undefined;const externalIdentifier=text(raw.externalIdentifier);return{title:values.title!,publisher:values.publisher!,sourceType:values.sourceType!,canonicalUrl:values.canonicalUrl!,retrievedAt:values.retrievedAt!,relation:values.relation!,rightsNote:values.rightsNote!,...(externalIdentifier?{externalIdentifier}:{}),...(publishedAt?{publishedAt}:{})};}
function fromEnvironment(env:Readonly<Record<string,string|undefined>>=process.env):SourceAcceptanceTransport{const baseUrl=env.PRIVATE_API_BASE_URL?.trim(),serviceCredential=env.PRIVATE_API_SERVICE_CREDENTIAL?.trim();if(!baseUrl||!serviceCredential)throw new Error("Private API configuration required.");return createSourceAcceptanceBff(createPrivateApiClient({baseUrl,serviceCredential}));}function text(v:unknown){return typeof v==="string"&&v.trim()?v.trim():undefined;}function date(v:string){return!Number.isNaN(Date.parse(v));}function uuid(v:string){return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v);}
