import { describe, expect, it, vi } from "vitest";
import { createSourceSubmissionReviewBff, loadSourceSubmissionReview } from "./source-submission-review-bff";
const editor = { actorId: "google:113355779900", email: "editor@example.com" } as const;
const value = { id: "submission-1", kind: "transcript", originalIdentifier: "government-video", submittedBy: "google:113355779900", submittedAt: "2026-08-07T00:00:00.000Z", rightsNote: "Rights cleared.", processingStatus: "ready-for-review", proposal: { proposedTopic: "Singapore government", confidence: .86, rationale: "Relevant", candidateClaims: [{ statement: "Parliament debates Bills.", excerpt: "Parliament considers Bills.", confidence: .8, rationale: "Direct" }], draft: { templateVersion: "v1", title: "How Parliament works", sections: [{ section: "One-sentence explanation", body: "Parliament debates laws." }] } } };
describe("Source Submission review BFF", () => {
  it("uses the private editor query seam", async () => { const query = vi.fn().mockResolvedValue(value); await expect(loadSourceSubmissionReview(editor, "submission-1", { transport: createSourceSubmissionReviewBff({ query }) })).resolves.toMatchObject({ kind: "available", submission: { id: "submission-1" } }); expect(query).toHaveBeenCalledWith({ path: "/v1/editorial/source-submissions/submission-1" }); });
  it("keeps missing and unavailable data distinct", async () => { await expect(loadSourceSubmissionReview(editor, "", { transport: { getSourceSubmission: vi.fn() } })).resolves.toEqual({ kind: "not-found" }); await expect(loadSourceSubmissionReview(editor, "submission-1", { transport: { getSourceSubmission: vi.fn().mockResolvedValue(undefined) } })).resolves.toEqual({ kind: "not-found" }); await expect(loadSourceSubmissionReview(editor, "submission-1", { transport: { getSourceSubmission: vi.fn().mockRejectedValue(new Error("private")) } })).resolves.toEqual({ kind: "unavailable" }); });
  it("rejects malformed responses", async () => { await expect(loadSourceSubmissionReview(editor, "submission-1", { transport: createSourceSubmissionReviewBff({ query: vi.fn().mockResolvedValue({ id: "submission-1" }) }) })).resolves.toEqual({ kind: "unavailable" }); });
});
