#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

RUNTIME_ENV_FILE="/etc/kopicontext/private-runtime.env"
TUNNEL_ENV_FILE="/etc/kopicontext/cloudflared.env"
REPOSITORY_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE="$RUNTIME_ENV_FILE"

banner "KopiContext · OMV private runtime"

stage "Host preflight"
say "Run this wizard from a full KopiContext checkout on the OMV host, as root."
say "It creates protected server-only files; it never sends a secret to GitHub."
if [[ "$EUID" -ne 0 ]]; then
  warn "Re-run exactly as: sudo bash scripts/setup-omv-private-runtime.sh"
  exit 1
fi
for command in docker git openssl; do
  if ! command -v "$command" >/dev/null 2>&1; then
    warn "Missing required command: $command"
    exit 1
  fi
done
step "Confirm Docker is working and this checkout is the intended repository."
docker version --format 'Docker client {{.Client.Version}}' || exit 1
git -C "$REPOSITORY_ROOT" remote -v | head -n 2
pause "Press Enter when the host and repository look correct."

stage "Dedicated deployment identity"
say "GitHub Actions will run only deployment work as kopi-deploy."
warn "Membership in the Docker group is effectively privileged host access."
if id -u kopi-deploy >/dev/null 2>&1; then
  note "kopi-deploy already exists; leaving its account intact."
else
  confirm "Create the dedicated kopi-deploy account now" || exit 1
  useradd --create-home --shell /bin/bash kopi-deploy
fi
usermod -aG docker kopi-deploy
install -d -m 755 -o kopi-deploy -g kopi-deploy /opt/actions-runner
say "Created/checked /opt/actions-runner. A new login is required before new Docker-group membership applies."
pause "Press Enter to continue."

stage "Private runtime secrets"
say "These values remain only in $RUNTIME_ENV_FILE (mode 600)."
step "Use only URL-safe random values, or URL-encode passwords in the two DATABASE_URL values."
ask POSTGRES_DB "Database name [recommend kopi_context]:"
[[ -n "$POSTGRES_DB" ]] || POSTGRES_DB="kopi_context"
ask POSTGRES_USER "Bootstrap admin role [recommend kopi_bootstrap]:"
[[ -n "$POSTGRES_USER" ]] || POSTGRES_USER="kopi_bootstrap"
ask_secret POSTGRES_PASSWORD "Bootstrap admin password (generate with: openssl rand -hex 36):"
ask POSTGRES_MIGRATION_USER "Migration role [recommend kopi_migrator]:"
[[ -n "$POSTGRES_MIGRATION_USER" ]] || POSTGRES_MIGRATION_USER="kopi_migrator"
ask_secret POSTGRES_MIGRATION_PASSWORD "Migration password (generate with: openssl rand -hex 36):"
ask POSTGRES_API_USER "API role [recommend kopi_api]:"
[[ -n "$POSTGRES_API_USER" ]] || POSTGRES_API_USER="kopi_api"
ask_secret POSTGRES_API_PASSWORD "API password (generate with: openssl rand -hex 36):"
ask_secret PRIVATE_API_SERVICE_CREDENTIAL "Private API service credential (generate with: openssl rand -hex 48):"
for key in POSTGRES_PASSWORD POSTGRES_MIGRATION_PASSWORD POSTGRES_API_PASSWORD PRIVATE_API_SERVICE_CREDENTIAL; do
  [[ -n "${!key}" ]] || { warn "$key cannot be empty."; exit 1; }
done
MIGRATION_DATABASE_URL="postgres://${POSTGRES_MIGRATION_USER}:${POSTGRES_MIGRATION_PASSWORD}@postgres:5432/${POSTGRES_DB}"
DATABASE_URL="postgres://${POSTGRES_API_USER}:${POSTGRES_API_PASSWORD}@postgres:5432/${POSTGRES_DB}"
install -d -m 750 -o root -g kopi-deploy /etc/kopicontext
touch "$RUNTIME_ENV_FILE"
chown root:kopi-deploy "$RUNTIME_ENV_FILE"
chmod 640 "$RUNTIME_ENV_FILE"
write_env POSTGRES_DB "$POSTGRES_DB"
write_env POSTGRES_USER "$POSTGRES_USER"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env POSTGRES_MIGRATION_USER "$POSTGRES_MIGRATION_USER"
write_env POSTGRES_MIGRATION_PASSWORD "$POSTGRES_MIGRATION_PASSWORD"
write_env POSTGRES_API_USER "$POSTGRES_API_USER"
write_env POSTGRES_API_PASSWORD "$POSTGRES_API_PASSWORD"
write_env MIGRATION_DATABASE_URL "$MIGRATION_DATABASE_URL"
write_env DATABASE_URL "$DATABASE_URL"
write_env PRIVATE_API_SERVICE_CREDENTIAL "$PRIVATE_API_SERVICE_CREDENTIAL"

stage "First private-runtime deployment"
say "This starts Postgres, applies checked-in migrations, and starts the API. No host port is opened."
confirm "Start the private Docker stack now" || exit 1
docker compose --project-directory "$REPOSITORY_ROOT" --env-file "$RUNTIME_ENV_FILE" \
  -f "$REPOSITORY_ROOT/compose.private-runtime.yaml" up -d --build
docker network inspect kopicontext-private_private_api >/dev/null
say "Private API network created: kopicontext-private_private_api"
pause "Press Enter after migrations and the API container are healthy."

stage "Cloudflare tunnel and hostname"
say "Create a new remotely managed tunnel named kopi-private-api. Do not alter your existing host connector."
open_url "https://one.dash.cloudflare.com/"
step "Go to Networking → Tunnels → Create a tunnel, name it kopi-private-api, and choose Docker."
step "Copy only the token from Cloudflare's Docker command. Do not run Cloudflare's command on the host."
ask_secret TUNNEL_TOKEN "Paste the new tunnel token:"
ask PRIVATE_API_BASE_URL "Public HTTPS hostname [for example https://api.example.com]:"
[[ -n "$TUNNEL_TOKEN" && -n "$PRIVATE_API_BASE_URL" ]] || { warn "The tunnel token and hostname are required."; exit 1; }
ENV_FILE="$TUNNEL_ENV_FILE"
touch "$TUNNEL_ENV_FILE"
chown root:kopi-deploy "$TUNNEL_ENV_FILE"
chmod 640 "$TUNNEL_ENV_FILE"
write_env TUNNEL_TOKEN "$TUNNEL_TOKEN"
write_env KOPI_PRIVATE_API_NETWORK "kopicontext-private_private_api"
ENV_FILE="$RUNTIME_ENV_FILE"

stage "Tunnel connector and route"
say "The connector has Docker-only access to the API service name api:3001. It does not open port 3001 on OMV."
docker compose --project-directory "$REPOSITORY_ROOT" --env-file "$TUNNEL_ENV_FILE" \
  -f "$REPOSITORY_ROOT/compose.cloudflare-tunnel.yaml" up -d
open_url "https://one.dash.cloudflare.com/"
step "Open Networking → Tunnels → kopi-private-api → Routes → Add a public hostname."
step "Set your chosen hostname. For Service, choose HTTP and enter api:3001. Save the route."
step "Do not point the route at localhost, the OMV IP address, or an exposed port."
pause "Press Enter after Cloudflare reports the connector healthy and the route is saved."

stage "GitHub protection and Vercel handoff"
open_url "https://github.com/HiokKuek/KopiContext/settings/environments"
step "Create the home-production environment and require your approval before deployment."
open_url "https://github.com/HiokKuek/KopiContext/settings/branches"
step "Protect main: require pull requests and the Verify check; restrict who may push."
open_url "https://vercel.com/dashboard"
step "In the KopiContext project's Production environment, set server-only PRIVATE_API_BASE_URL to: $PRIVATE_API_BASE_URL"
step "Set PRIVATE_API_SERVICE_CREDENTIAL to the exact credential entered in Stage 3. Also set Google OAuth and editor variables from .env.example."
step "Redeploy Vercel, then visit the public site and sign in as the configured editor."
say "Finally, verify Docker-side health with: $REPOSITORY_ROOT/scripts/deploy-private-runtime.sh"
pause "Press Enter after the approval gate and Vercel values are configured."

stage "GitHub Actions deployment runner"
say "Set the approval gate first. Use a repository-level runner only; the workflow never runs it for pull requests."
open_url "https://github.com/HiokKuek/KopiContext/settings/actions/runners/new"
step "Choose Linux and x64, then copy the current download and extraction commands from GitHub."
step "Run them as kopi-deploy in /opt/actions-runner. In the final config command add: --labels kopi-private-deploy"
step "After configuration, as root run: /opt/actions-runner/svc.sh install kopi-deploy && /opt/actions-runner/svc.sh start"
step "Return to GitHub and confirm the runner is Idle with the kopi-private-deploy label."
pause "Press Enter after the runner is online."

finish
