"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { EditorAccessDeniedError, EditorAuthenticationRequiredError, requireEditorSession } from "@/modules/auth/editor-auth";
import { createEditorialDraft } from "@/platform/web/editorial-draft-bff";
import type { TemplateV1RevisionContent } from "@/modules/editorial/create-human-revision-command";
export type EditorialDraftActionState = Readonly<{kind:"idle"|"invalid"|"rejected"|"unavailable";message:string}>;
export const initialEditorialDraftActionState: EditorialDraftActionState = { kind: "idle", message: "" };
export async function createEditorialDraftAction(_: EditorialDraftActionState, form: FormData): Promise<EditorialDraftActionState> { const editor = await requireEditor(); const content = contentOf(form); if (!content) return { kind: "invalid", message: "Complete the required fields. Key terms use “Term :: definition”." }; const result = await createEditorialDraft(editor, { topic: { slug: text(form.get("slug")) ?? "", title: text(form.get("title")) ?? "", description: text(form.get("description")) ?? "" }, content }); if (result.kind === "success") { revalidatePath("/editor"); redirect(`/editor/briefings/${result.briefingId}`); } return result; }
function contentOf(form: FormData): TemplateV1RevisionContent | undefined { const oneSentenceExplanation=text(form.get("oneSentenceExplanation")),thirtySecondOverview=text(form.get("thirtySecondOverview")),fiveMinuteExplanation=text(form.get("fiveMinuteExplanation")),whyPeopleCare=text(form.get("whyPeopleCare")),singaporeSeaAngle=text(form.get("singaporeSeaAngle")); if(!oneSentenceExplanation||!thirtySecondOverview||!fiveMinuteExplanation||!whyPeopleCare||!singaporeSeaAngle)return; const keyTerms=lines(form.get("keyTerms")).map(x=>{const [term,...d]=x.split("::");return {term:term?.trim(),definition:d.join("::").trim()};});if(keyTerms.some(x=>!x.term||!x.definition))return; return {oneSentenceExplanation,thirtySecondOverview,fiveMinuteExplanation,whyPeopleCare,singaporeSeaAngle,keyTerms:keyTerms as {term:string;definition:string}[],entities:lines(form.get("entities")),debates:lines(form.get("debates")),questionsToAsk:lines(form.get("questionsToAsk")),mistakesToAvoid:lines(form.get("mistakesToAvoid"))}; }
function text(v:FormDataEntryValue|null){return typeof v==="string"&&v.trim()?v.trim():undefined}function lines(v:FormDataEntryValue|null){return typeof v==="string"?v.split("\n").map(x=>x.trim()).filter(Boolean):[]}async function requireEditor(){try{return await requireEditorSession()}catch(e){if(e instanceof EditorAuthenticationRequiredError)redirect("/api/auth/signin?callbackUrl=/editor/briefings/new");if(e instanceof EditorAccessDeniedError)redirect("/api/auth/error?error=AccessDenied");throw e}}
